from setuptools import setup, find_packages
setup(
    name='orionclient',
    version='0.0.2',
    description='pure python fiware orion client',
    url='https://github.com/openath/orion-python-client',
    author='Andy Robinson',
    author_email='andy@reportlab.com',
    classifiers=[
            'Development Status :: 3 - Alpha',
            'Intended Audience :: Developers',
            'Topic :: Software Development :: Libraries :: Python Modules',
            'Programming Language :: Python :: 2',
            'Programming Language :: Python :: 2.7',
            'Programming Language :: Python :: 3',
            'Programming Language :: Python :: 3.3',
            'Programming Language :: Python :: 3.4',
            'Programming Language :: Python :: 3.5',
            ],
    keywords='orion client',
    install_requires=['requests'],
    license='BSD',
    package_dir={'': 'src'},
    py_modules=['orionclient'],
    )
